### PR TITLE
updates

### PR DESCRIPTION
**Pull request by scottaohara**
less updates:
rename .small-btn back to .btn-small to retain naming convention of other class names & to match what is on the demo site & sass files. (further renaming of this may be in order)

general.less - combine font declarations into 1 shorthand rule.

place text area, input, addon-front{} selector group at top of file.  update textarea, input selector group focus state to take up less characters.

navbar.less
combine .navbar declarations into one file, putting comments around the max-height: 1.5em w/in the combined ruleset

sass updates:

remove messages.scss from import list, remove.scss extensions on import as they aren't required

update css comment to sass comment in table.scss, headings, icons.scss and buttons.scss

update outline: none; to outline: 0; and change border: 1px solid #5ab to border-color: #5ab for focus state of text, input selector.

button.scss - bring over new styling from less file

navbar.scss - bring over some of the styling from navbar.less -- need to discuss further before additional updates

### CODE REVIEW

**Comment by owenversteeg** [comment]
looks great, thanks! I especially like your change from `border: 1px solid #5ab;` to `border-color: #5ab;`

However, my change from `.btn-small` to `.small-btn` was intentional - if you see [line 23 of buttons.less](https://github.com/OwenVersteeg/min/blob/gh-pages/less/buttons.less#L23) we apply styles to classless buttons using the selector `.btn:not([class*='btn-'])`, and this selector matches `.btn-small` and not `.small-btn`. Therefore, we have to use `.small-btn`

I can't come up with a way to do this that'd allow using `.btn-small` (I ruled out `.btn:not(.btn-a):not(.btn-b).not(.btn-c)` because of size concerns) but if you can think of a way let me know.

**Comment by scottaohara** [comment]
just added a new commit to negate the need for the btn:not selector

to see an example of it working: http://www.scottohara.me/min/

you may notice that the background color of the colored buttons is used as a border for the buttons.  This keeps them all the same size w/out having to change the padding between the base / colored states.  

on hover of the colored buttons, the border stays the original button color.  It's not super noticeable, but I like this because 1. it gives the buttons a slight highlight around the border when hovered & 2. it keeps the design consistent w/ the normal buttons that have the black border that doesn't change on hover.

Let me know what you think of these changes, and whether I should revert the removal of btn:not or if you like that change.

Going to go read what you posted about the navbar stuff in the other thread now

**Comment by owenversteeg** [comment]
The only thing that worries me is the space we lose by setting `border-color` and `color` on all the colored button classes. It adds 67 bytes minified and gzipped, and Min's already at 1078 bytes (including the navbar changes, which added about 200 bytes.) I think the visual effect can be nice but I'm not sure how I'd compensate for the extra bytes.

Basically, I don't think the naming consistency is worth the extra 67 bytes. If you can think of a way to keep naming consistency but not increase file size I'd be all for it, but I don't think this is possible.

**Comment by scottaohara** [comment]
i've reverted back to using the :not selector from your previous comment.

The only other method we could implement is adding an extra "-" for the colored buttons.
e.g. .btn--a{}

Then the not selector could be: .btn:not([class*='btn--']) and work with the btn-sm class.  That's the last idea I got on that topic I think.

The :not selector doesn't work prior to IE9.  Is that not an issue for min?  Are you looking for these to work in all older browsers?

**Comment by owenversteeg** [comment]
I didn't realize that `:not` didn't work before IE9. Thanks for pointing that out. As it turns out, attribute selectors only work in IE7+. 

That's a dealbreaker, as Min supports IE5.5+. I also don't like the idea of breaking the naming convention, and I think using double dashes would also break the naming convention.

That said, there's an easy way out of this: making classless buttons black, orange, grey, or yellow. This is by far my favorite solution, as it not only maintains IE5.5 compatibility but also saves a considerable amount of space. Here are some possible button looks:

New button styles

Let me know which is your favorite.

**Comment by scottaohara** [comment]
i vote for either the black or grey versions. i think either would be a good 'base' color choice

**Comment by scottaohara** [comment]
I went ahead and implemented the rest of the updates that needed to happen to the Sass version to get it inline with the LESS version.

I also implemented what we were talking about here, and removed the :not selectors and gave base buttons a black base state with #aaa as a hover. (we can update to other colors if you feel differently)

with these updates, and some other modifications I made to the .navbar (renamed .nav and redid some of the markup and CSS selectors) I was able to get the framework to minify/gzip to 995 bytes.

The only thing that was lost in doing this was I removed the rounded corners from the buttons.

If I remember correctly, this was going to be implemented with the new button styles anyway?  If not, then I do have an argument as to why squared corners may have more of a place in min than rounded.  but I don't need to get into that unless you have an issue with this solution.

You can see the examples page in action, using the compiled sass output (not minified so you can easily traverse the file if you want to check it out)

http://www.scottohara.me/min/test.html

**Comment by owenversteeg** [comment]
Although I prefer the idea of a black background, it means that we can't make the background darker on hover; thus, I prefer a gray background. I've implemented this in the relevant less file (on this PR branch) using `#999`, `#888`, and `#777` respectively as bg, hover, and active colors.

**Comment by owenversteeg** [comment]
The latest commit gets us down to 1009 with rounded corners.

**Comment by owenversteeg** [comment]
These latest commits bring us down to 1008, rounded corners included.

**Comment by owenversteeg** [comment]
Woo! I just cut it down to 991. With rounded corners. (See the above commit.)

I'm exhausted, it's 3am my time. It looks like the last few challenges for the 2.0 launch are migrating the various Sass/LESS changes back and forth, getting a new site, fixing the Bootstrap to Min converter, and Bootstrap feature parity.

**Comment by scottaohara** [comment]
Awesome, i'll take a look through your further changes tonight and port them over to the Sass branch here.

After I update and verify the changes, will it be good to merge the branch?

This has been fun. Thanks for letting me work on this project with you :)

**Comment by scottaohara** [comment]
did you review the changes I had made to the navbar file?

I revised some of the code which produced the same results as what you had, but significantly reduced the selector for the close button and a few other changes here and there (like removing position: relative from the .navbar (renamed .nav) and instead using line-height: 1.5em) also, revised the markup to read like

```
<nav class="nav">
<div class="container">
```

lemme know what you think before i move ahead with revising the navbar.scss more

**Comment by owenversteeg** [comment]
Earlier today I realized that I had to (under the terms of the MIT license) include a notice at the top saying `/*Copyright (c) 2014 Owen Versteeg; MIT licensed*/`. Thus, I made some changes to make Min even smaller, bringing the total size (sans copyright) to 965 bytes, or the total size (with copyright+license) to 1008 bytes exactly. If you know any lawyers, ask if it's OK to reduce the copyright down to `/*(c) 2014 Owen Versteeg; MIT licensed*/` - we save 7 bytes minified and gzipped.

re: your first comment - You're very welcome! Thank you for all your help! You can go ahead and merge the branch as soon as you feel it's ready.

re: your second comment - I looked over the changes; they look great. I can replicate them in the LESS folder tomorrow, compile them, and see if they broke anything on iOS or old IEs. Hopefully the byte savings is enough to push Min back down to 995. If not, I'll change the base font-size to 14px (and I'll update all the em font-sizes in respect to this), which will give us a few more bytes. If you want to you can also go ahead and revise navbar.scss more.

**Comment by scottaohara** [comment]
that commit title should read "moar"  stupid auto correct.

anyway, I've made the rest of my updates to the SCSS files, and ported over a few changes you made last night.

I started some work on the navbar.less file, but have mostly left it as-is (reduced all references of .navbar to .nav and reduced the selector string for the close button)

Some additional insight into some of my edits:
One reason I removed the styling of the html5 nav element, and made the base a .nav class, is that I think there's a use case for that element to not always have a black background (a footer nav for example).

**Comment by owenversteeg** [comment]
I'm glad you updated the moat - it was filling with dirt and the alligator module was out-of-date :)

It looks like your changes make the navbar go from

```
<nav>
    <div class="navbar container" tabindex="-1" onclick="this.focus()">
        <a class="pagename navbar-link" href="#">Min Framework</a>
        <a class="navbar-link" href="#">One</a>
        <a class="navbar-link" href="#">Two</a> 
        <a class="navbar-link" href="#">Three</a>
    </div>
</nav>
<button class="close btn small-btn">×</button>
```

(old navbar HTML)

to 

```
<nav class="nav" tabindex="-1" onclick="this.focus()">
    <div class="container">
        <a class="pagename nav-link" href="#">Min Framework</a>
        <a class="nav-link" href="#">One</a>
        <a class="nav-link" href="#">Two</a> 
        <a class="nav-link" href="#">Three</a>
    </div>
</nav>
<button class="btn btn-small btn-close">×</button>
```

(new navbar HTML)

Is this correct? If so, there are a few changes that need to be made to the CSS to fix how everything looks. Namely, the .btn-close selector should become .btn.btn-close (this increases the specificity, which forces the background to be black even on hover), the

**Comment by owenversteeg** [comment]
Okay, with the latest changes (yours and mine combined) we're down to 994 bytes with a copyright notice. Adding two spaces for clarity brings us up to 995: `/* Copyright (c) 2014 Owen Versteeg; MIT licensed */` I get these size results when compiling the LESS version.

I think the LESS version right now is golden; the only changes left are:
- [ ] Bringing the Sass version up to date with the LESS version's changes.
- [ ] New site
- [ ] Fixing the Bootstrap to Min converter
- [ ] Bootstrap feature parity

Once you can get the Sass version to produce the same output as the LESS version you can go ahead and merge (yay!)

**Comment by scottaohara** [comment]
looks like I got it down to 977b without the copyright notice (are you importing that after the fact?)

the only thing that seems strange to me is the small screen menu icon / btn-close styling.  the three lines don't look consistent in my tests of both the less and sass version, and the X isn't covered up anymore.

I tested both versions in Firefox and chrome on my mac.

I unfortunately don't have more time to look into this tonight.  but I'll test some more tomorrow if you don't have any ideas.

**Comment by scottaohara** [comment]
alright.  I found a solution to the navbar icon issue i had found, and it probably makes sense for you to take a look at it for the less version too.

final gz size is 969b w/ this commit.

Merging into master.  yay.

**Pull request merged**
