### PR TITLE
update button classes to reduce file size & increase reusability

### PR DESCRIPTION
**Pull request by scottaohara**
Hi there,

I was hoping I could contribute the following to your project.  

In an effort to cut down on file size & make the button classes more modular, I reduced the selectors of the buttons to no longer be attached to the <button> element.

now .btn-a, b, c, & small can be combined with a generic .btn class (which has the same styles as <button> and this class combo can be added to <a> elements, inputs with a type of submit or anything that one would like to look like a button.

I used terminal to run a gzip compression on the minified file and these edits reduced the file size to 978 bytes (ran a compression in the same way on the original, which clocked in at 980).

### CODE REVIEW

**Comment by scottaohara** [comment]
If you're at all interested, I also created another branch and converted Min over to Sass.

Anyway, regardless if you want to merge or not, thanks for taking a look.  It was fun playing around with this.

**Comment by owenversteeg** [comment]
The SASS version looks interesting, but I'm somewhat concerned about maintaining both a SASS and LESS version. It'd increase the amount of work someone has to do to a) build Min and b) add some code.

Do you think there's substantial value added by a SASS version? Do you think it'd be better than a LESS version?

**Comment by owenversteeg** [comment]
Concerning this pull request (about updating button styles) I think it looks good, but I see two main issues:
- Buttons on the navbar have gray text. This can be fixed with by adding `:not(.btn)` to line 20 of navbar.less. Can you do this?
- For some reason you also updated the entireframework.min.css file but you also added some unnecessary spaces. In your second commit it looks like you fixed this, but I'm not entirely sure. Can you check that there are none? (Personally, I'd just build it from your latest LESS and compare the files.)

Once you do these two things, I'll merge it - it looks like a cool idea. I especially like the navbar buttons.

**Comment by scottaohara** [comment]
Hey, thanks for taking a look at this.

Concerning your points about the button pull request:

Does :not(.btn) need to be added?  Adding an element with classes .btn & .btn-small gets it into the navbar just fine, and the text stays white.  Adding the class of .navbar-link doesn't really do anything to affect the size or style of the button, aside from turning the text grey, which is what we want to avoid anyway.  I'm happy to comply and add your suggestion to the .navbar-link class, but in the spirit of trying to keep the code footprint as small as possible, I thought I should bring this up.

As for the entireframework.min.css, I had minified that using two different methods. I saw that the first hadn't cut out the extra spaces, so I went to a second that did in the next commit.  Really the only reason I even included it with the commit was so that you could see the difference in file sizes without having to run a compile yourself.

As an aside, I'm also submitting an update to the navbar.less and headings.less with this comment.
In navbar.less, I converted the colors black and white over to their shorthand hex values to be consistent with other declarations of these colors in the framework, as well as to cut down on characters.

In headings.less, I decoupled .title from compiling as h1.title, so now it can be applied to any heading or text element.

I did not update the minified css file with these changes, as I want to hear back from you on the :not(.btn) issue and per your comments it seems kind of unnecessary.

Thanks

**Comment by owenversteeg** [comment]
You're right, the .not isn't needed. This is why I shouldn't say things when I'm tired :)

Thanks for replacing the black and white with their colors - I intended to do that but I guess I didn't.

I'm merging it in now, but in the future please don't update entireframework.min.css - I only update that after extensive browser testing. (I don't think it's an issue with this commit, but for other commits it might be.)

Congratulations, you're the second contributor to Min!

**Comment by scottaohara** [comment]
thank you.

and yes, in the future I agree, there's no reason to update the min.css

**Pull request merged**
