### PR TITLE
Styles for password fields

### PR DESCRIPTION
**Pull request by Eun**

### CODE REVIEW

**Comment by chilic** [comment]
+1

**Comment by scottaohara** [comment]
what is the benefit in doing this on a global scale vs for a specific usage of the framework?

i ask because if we accept a specific input type, then why not bring in all of the input types, like date, search, url, etc?  that would quickly lead to going beyond the 1kb cap of the framework.

would a better solution here instead be to include a single `.txt-input` class that could be applied to any text input type?

**Comment by chilic** [comment]
@scottaohara It's makes sense. Agree with you.

**Comment by scottaohara** [comment]
@owenversteeg what are your thoughts on this?  should we add an ```.input``` class?

i feel like we spoke of this before but maybe i'm not remembering correctly?

**Pull request closed without merging**
